/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    attachments: Attachment;
    avatars: Avatar;
    posts: Post;
    'post-banners': PostBanner;
    users: User;
  };
  globals: {};
}
export interface Attachment {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Avatar {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Post {
  id: string;
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  banner?: string | PostBanner;
  slug: string;
  minutesToRead: number;
  author: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface PostBanner {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  fullName: string;
  bio: string;
  avatar?: string | Avatar;
  roles?: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
